"""
Export paragraph embeddings as a Blender-compatible 3D PLY mesh.

Example:

python visualization/3D.py --book alice_wonderland --model bge-m3
"""

import argparse
import json
import os

from matplotlib import colormaps
import numpy as np
from umap import UMAP


OCTAHEDRON_FACES = (
  (0, 2, 4),
  (2, 1, 4),
  (1, 3, 4),
  (3, 0, 4),
  (2, 0, 5),
  (1, 2, 5),
  (3, 1, 5),
  (0, 3, 5),
)


def add_point(vertices, faces, center, radius, color):
  """Add a small octahedron so each embedding is visible in Blender."""
  start = len(vertices)
  x, y, z = center
  r, g, b = color
  vertices.extend(
    [
      (x + radius, y, z, r, g, b),
      (x - radius, y, z, r, g, b),
      (x, y + radius, z, r, g, b),
      (x, y - radius, z, r, g, b),
      (x, y, z + radius, r, g, b),
      (x, y, z - radius, r, g, b),
    ]
  )
  faces.extend(tuple(start + index for index in face) for face in OCTAHEDRON_FACES)


def add_tube(vertices, faces, start_point, end_point, radius, sides=6):
  """Add a narrow tube between consecutive paragraphs."""
  direction = end_point - start_point
  length = np.linalg.norm(direction)
  if length == 0:
    return

  direction /= length
  helper = np.array([0.0, 0.0, 1.0])
  if abs(np.dot(direction, helper)) > 0.9:
    helper = np.array([0.0, 1.0, 0.0])

  axis_1 = np.cross(direction, helper)
  axis_1 /= np.linalg.norm(axis_1)
  axis_2 = np.cross(direction, axis_1)
  first = len(vertices)
  tube_color = (70, 70, 70)

  for point in (start_point, end_point):
    for side in range(sides):
      angle = 2 * np.pi * side / sides
      offset = radius * (np.cos(angle) * axis_1 + np.sin(angle) * axis_2)
      x, y, z = point + offset
      vertices.append((x, y, z, *tube_color))

  for side in range(sides):
    next_side = (side + 1) % sides
    a = first + side
    b = first + next_side
    c = first + sides + side
    d = first + sides + next_side
    faces.append((a, c, b))
    faces.append((b, c, d))


def write_ply(coords, values, output_path, point_size=0.008):
  """Write colored points and the story path as one ASCII PLY mesh."""
  extent = float(np.max(np.ptp(coords, axis=0)))
  point_radius = max(extent * point_size, 1e-6)
  tube_radius = point_radius * 0.22

  value_range = np.ptp(values)
  normalized = np.zeros_like(values, dtype=float)
  if value_range > 0:
    normalized = (values - np.min(values)) / value_range

  rgb_colors = (colormaps["plasma"](normalized)[:, :3] * 255).astype(np.uint8)
  vertices = []
  faces = []

  for coord, color in zip(coords, rgb_colors):
    add_point(vertices, faces, coord, point_radius, tuple(int(c) for c in color))

  for index in range(len(coords) - 1):
    add_tube(
      vertices,
      faces,
      coords[index],
      coords[index + 1],
      tube_radius,
    )

  with open(output_path, "w", encoding="ascii") as file:
    file.write("ply\n")
    file.write("format ascii 1.0\n")
    file.write("comment Paragraph embedding storyline generated by 3D.py\n")
    file.write(f"element vertex {len(vertices)}\n")
    file.write("property float x\n")
    file.write("property float y\n")
    file.write("property float z\n")
    file.write("property uchar red\n")
    file.write("property uchar green\n")
    file.write("property uchar blue\n")
    file.write(f"element face {len(faces)}\n")
    file.write("property list uchar int vertex_indices\n")
    file.write("end_header\n")

    for x, y, z, red, green, blue in vertices:
      file.write(f"{x:.7g} {y:.7g} {z:.7g} {red} {green} {blue}\n")
    for face in faces:
      file.write(f"3 {face[0]} {face[1]} {face[2]}\n")


def main():
  parser = argparse.ArgumentParser()
  parser.add_argument("--book", required=True, type=str)
  parser.add_argument("--model", required=True, type=str)
  parser.add_argument("--seed", default=0, type=int)
  parser.add_argument("--neighbors", default=5, type=int)
  parser.add_argument("--min-dist", default=0.1, type=float)
  parser.add_argument(
    "--point-size",
    default=0.008,
    type=float,
    help="Point radius as a fraction of the visualization's largest dimension",
  )
  args = parser.parse_args()

  book_dir = os.path.join("books", args.book)
  processed_file = os.path.join(book_dir, "processed.json")
  embedding_file = os.path.join(book_dir, "embeddings", args.model, "embeddings.npy")

  with open(processed_file, "r") as file:
    processed = json.load(file)

  paragraphs = processed["paragraphs"]
  paragraph_ids = np.arange(len(paragraphs))
  embeddings = np.load(embedding_file)

  print("Running 3D UMAP...")
  umap = UMAP(
    n_components=3,
    n_neighbors=args.neighbors,
    min_dist=args.min_dist,
    random_state=args.seed,
  )
  coords = umap.fit_transform(embeddings)

  output_dir = os.path.join("output", args.book, args.model, "3d")
  os.makedirs(output_dir, exist_ok=True)
  np.save(os.path.join(output_dir, "umap.npy"), coords)

  output_path = os.path.join(output_dir, "storyline.ply")
  write_ply(coords, paragraph_ids, output_path, point_size=args.point_size)

  print()
  print("Done. Import this file into Blender:")
  print(output_path)


if __name__ == "__main__":
  main()
